version: "3"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 20000:5432
    volumes:
      - pgdata-buynow:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    restart: always
    ports:
      - 18300:6379

volumes:
  pgdata-buynow: